version: '3.1'
services:
  db:
    image: postgres:16
    container_name: testing-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: testing-db